CREATE DATABASE RECIPEDB;
USE RECIPEBD;

CREATE TABLE Users(
UserID INT AUTO_INCREMENT PRIMARY KEY,
UserName Varchar(50) NOT NULL,
Password VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
Contact VARCHAR(20)
);
