GET http://localhost:4000/get-recipe

###
GET http://localhost:4000/get-recipe/1

###




###
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjUsIkVtYWlsIjoia2VsdmlubXVzYXVAZ21haWwuY29tIiwiaWF0IjoxNzMyNjUzNDIxfQ.3gQhXM8Y0s-IiUF4SNI5Ptc3HsvZB4YjBeJNViGL_k4

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "Email": "kelvinmusau@gmail.com",
  "Password": "kevo"
}

###
GET http://localhost:4000/user/bridgitmogeni@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjUsIkVtYWlsIjoia2VsdmlubXVzYXVAZ21haWwuY29tIiwiaWF0IjoxNzMyNjUzNDIxfQ.3gQhXM8Y0s-IiUF4SNI5Ptc3HsvZB4YjBeJNViGL_k4

###
GET http://localhost:4000/users/Female
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjUsIkVtYWlsIjoia2VsdmlubXVzYXVAZ21haWwuY29tIiwiaWF0IjoxNzMyNjUzNDIxfQ.3gQhXM8Y0s-IiUF4SNI5Ptc3HsvZB4YjBeJNViGL_k4

###
GET http://localhost:4000/users/Male
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjUsIkVtYWlsIjoia2VsdmlubXVzYXVAZ21haWwuY29tIiwiaWF0IjoxNzMyNjUzNDIxfQ.3gQhXM8Y0s-IiUF4SNI5Ptc3HsvZB4YjBeJNViGL_k4
